RULES = [
    {
        "id": "role-override",
        "name": "Role override attempt",
        "severity": "critical",
        "description": "Attempts to redefine the AI's role or identity",
        "patterns": [
            r"you\s+are\s+now\s+(a|an)\s",
            r"from\s+now\s+on\s+you\s+(are|will|must|should)\s",
            r"forget\s+(everything|all|your|previous|prior)",
            r"ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|rules?|prompts?|context)",
            r"disregard\s+(all\s+)?(previous|prior|your)\s",
            r"act\s+as\s+(if\s+you\s+(were|are)|a|an)\s",
            r"pretend\s+(you\s+are|to\s+be)\s",
            r"you\s+must\s+now\s+obey",
            r"your\s+new\s+(role|instruction|persona|identity|purpose)\s",
            r"stop\s+being\s+(a|an)\s+.{0,30}\s+and\s+(be|become)",
        ],
    },
    {
        "id": "system-impersonation",
        "name": "System message impersonation",
        "severity": "critical",
        "description": "Fake system-level messages embedded in content",
        "patterns": [
            r"\[\s*(system|admin|root|assistant)\s*(message|prompt|instruction)?\s*\]",
            r"<<\s*(system|admin|root|override|internal)\s*>>",
            r"(developer|debug|maintenance|test|god)\s+mode",
            r"admin(istrator)?\s+override",
            r"emergency\s+(protocol|override|access)",
            r"this\s+is\s+a\s+system\s+message",
            r"authorized\s+by\s+(admin|system|developer|root)",
            r"SYSTEM\s*:\s*[A-Z]",
        ],
    },
    {
        "id": "instruction-extraction",
        "name": "Instruction extraction attempt",
        "severity": "high",
        "description": "Attempts to extract the system prompt or hidden instructions",
        "patterns": [
            r"(show|reveal|display|print|output|repeat|tell\s+me)\s+.{0,20}\s*(instructions?|prompt|rules?|configuration|guidelines)",
            r"what\s+(are|were)\s+your\s+(initial|original|system|hidden|secret|internal)\s+(instructions?|prompt|rules?)",
            r"(copy|paste|type\s+out)\s+.{0,20}\s*(system|original|initial)\s*(prompt|instructions?|message)",
            r"(give|send)\s+me\s+.{0,20}\s*(prompt|instructions?|rules?)",
            r"(read|recite)\s+.{0,15}\s*(back|aloud|out).{0,15}\s*(prompt|instructions?)",
            r"translate\s+your\s+(instructions?|prompt|rules?)\s+",
        ],
    },
    {
        "id": "jailbreak",
        "name": "Known jailbreak pattern",
        "severity": "critical",
        "description": "Contains known jailbreak prompt patterns",
        "patterns": [
            r"\bdo\s+anything\s+now\b",
            r"\bDAN\b",
            r"\bjailbreak(ed|ing)?\b",
            r"bypass\s+(your\s+)?(safety|content|ethical|security)\s*(filter|guard|policy|restriction|check)s?",
            r"(no|without|remove|disable|ignore)\s+(any\s+)?(ethical|moral|safety|content)\s*(guidelines?|restrictions?|filters?|boundaries|limitations?|rules?)",
            r"unfiltered\s+(mode|response|output|version)",
            r"(enable|activate|switch\s+to)\s+.{0,20}(unrestricted|unfiltered|uncensored)",
            r"pretend\s+(there\s+are|you\s+have)\s+no\s+(rules?|restrictions?|limitations?|filters?)",
        ],
    },
    {
        "id": "data-exfiltration",
        "name": "Data exfiltration attempt",
        "severity": "critical",
        "description": "Attempts to extract or transmit sensitive data",
        "patterns": [
            r"send\s+(this|the|all|every)\s+.{0,30}\s*(to|at)\s+",
            r"(forward|transmit|exfiltrate|upload|post)\s+.{0,30}\s*(to|at)\s+https?://",
            r"(include|embed|encode)\s+.{0,20}\s*(api|secret|token|key|password|credential)s?\s+in",
            r"(fetch|request|call|curl|wget)\s+.{0,10}https?://",
            r"webhook[.:/]",
            r"(pipe|redirect)\s+.{0,20}\s*(output|response|data|result)\s+to",
        ],
    },
    {
        "id": "context-breaking",
        "name": "Delimiter / context breaking",
        "severity": "high",
        "description": "Attempts to break out of the current context using delimiters",
        "patterns": [
            r"---\s*(end|begin|start)\s+(of\s+)?(system|user|assistant|context|instructions?)",
            r"```\s*(system|hidden|secret|internal|admin)",
            r"<\/?(?:system|instruction|admin|hidden|secret|internal)[^>]*>",
            r"\[\[(?:SYSTEM|ADMIN|OVERRIDE|HIDDEN|SECRET)\]\]",
            r"={3,}\s*(NEW|OVERRIDE|SYSTEM|REAL|ACTUAL)\s+",
            r"<!--\s*.{0,50}(instruction|ignore|override|system|admin)",
        ],
    },
]